server:
  port: 7600
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka/
zuul:
  routes:
    dm-user-customer: /user/**
# 修改git config文件，不需要启动文件，自动刷新
management:
  endpoints:
    web:
      exposure:
        include: dev
# 关闭过滤器 zuul 子项
#  SecondFilter:
#    pre:
#      disable: true